name: White Stone Industries
favicon: null
layout_spectrum: 0.32967409840784967
typography_spectrum: 0.010165754240006208
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3179408360738307
  lightness: 0.31908957939594984
  saturation: 0.03745747054927051
  rhythmicContrast: 0.22237415402196348
purpose: []
