name: White Stone Industries
favicon: null
layout_spectrum: 0.51043
typography_spectrum: 0.63882
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#212121'
    - '#ffffff'
    - '#858585'
    - '#dcdcdc'
    - '#adadad'
  brandStrength: 0.3179408360738307
  lightness: 0.31908957939594984
  saturation: 0.03745747054927051
  rhythmicContrast: 0
purpose: []
